services:
  - type: web
    name: api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        fromDatabase:
          name: database
          property: connectionString
    startCommand: npm start
    buildCommand: npm install
    repo: https://github.com/your-username/your-repo.git
    region: oregon
    plan: web.small
    env: nodejs
    network: locagest
    dependencies:
      - name: database
        type: database
        alias: database

databases:
  - name: database
    databaseName: locagest
    plan: data
    region: oregon
    env: mongodb
    network: locagest
